URL=https://demo.guru99.com/telecom/index.html
FNAME=Poojauyiwwe
LNAME=Sane
EMAIL=pooja24@gmail.com
ADRESS= pimple nagar road pune
MOBILENUMBER=7845651295
MONTHLYRETAL=456
FREELOCALMIN=42
FREEINTERNATIONALMIN=56
SMSPACK=200
LOCALCHARGES=8
INTERCHARGES=23
SMSPERCHARGES=12
COMPLETE=Congratulation you add Tariff Plan